In [1]:
import pandas as pd

In [11]:
df = pd.read_csv('employees.csv')

In [22]:
df.head()

,Employee ID,Name,Role,Department,Monthly Salary (EGP),Source,Referred By ID,Referral Bonus
0,EG-EMP-1000,Tarek Reda,Frontend Dev,Engineering,43833,Direct,NaN,0
1,EG-EMP-1001,Mostafa Ali,ML Engineer,Data Science,56644,Employee Referral,EG-EMP-1000,10000
2,EG-EMP-1002,Khaled Mahmoud,Data Scientist,Data Science,48157,LinkedIn,NaN,0
3,EG-EMP-1003,Khaled Mansour,ML Engineer,Data Science,36854,Recruiter,NaN,0
4,EG-EMP-1004,Hoda Soliman,Sales Executive,Sales/HR,35094,LinkedIn,NaN,0

In [26]:

df_joined = df.merge(
    df, 
    left_on='Referred By ID', 
    right_on='Employee ID', 
    suffixes=('_caller', '_other'),
    how='left'
)

df['Name'] = df_joined['Name_caller']
df['Referred By Name'] = df_joined['Name_other']

In [29]:
df.head()

,Employee ID,Name,Role,Department,Monthly Salary (EGP),Source,Referral Bonus,Referred By Name
0,EG-EMP-1000,Tarek Reda,Frontend Dev,Engineering,43833,Direct,0,NaN
1,EG-EMP-1001,Mostafa Ali,ML Engineer,Data Science,56644,Employee Referral,10000,Tarek Reda
2,EG-EMP-1002,Khaled Mahmoud,Data Scientist,Data Science,48157,LinkedIn,0,NaN
3,EG-EMP-1003,Khaled Mansour,ML Engineer,Data Science,36854,Recruiter,0,NaN
4,EG-EMP-1004,Hoda Soliman,Sales Executive,Sales/HR,35094,LinkedIn,0,NaN

In [28]:
df.drop('Referred By ID', axis=1, inplace=True)

In [30]:
df.to_csv('employees.csv', index=False)